# This file is generated with bin/generate_reporting_columns.rb, do not edit!
TNSPaymentsGateway::REPORTING_COLUMNS = %w(
  3DSecure.acsEci
  3DSecure.authenticationStatus
  3DSecure.authenticationToken
  3DSecure.enrollmentStatus
  3DSecure.xid
  3DSecureId
  airline.bookingReference
  airline.documentType
  airline.itinerary.leg.carrierCode
  airline.itinerary.leg.conjunctionTicketNumber
  airline.itinerary.leg.couponNumber
  airline.itinerary.leg.departureAirport
  airline.itinerary.leg.departureDate
  airline.itinerary.leg.departureTax
  airline.itinerary.leg.departureTime
  airline.itinerary.leg.destinationAirport
  airline.itinerary.leg.destinationArrivalTime
  airline.itinerary.leg.endorsementsRestrictions
  airline.itinerary.leg.exchangeTicketNumber
  airline.itinerary.leg.fare
  airline.itinerary.leg.fareBasis
  airline.itinerary.leg.fees
  airline.itinerary.leg.flightNumber
  airline.itinerary.leg.stopoverPermitted
  airline.itinerary.leg.taxes
  airline.itinerary.leg.travelClass
  airline.itinerary.numberInParty
  airline.itinerary.originCountry
  airline.passenger.firstName
  airline.passenger.lastName
  airline.passenger.middleName
  airline.passenger.specificInformation
  airline.passenger.title
  airline.planNumber
  airline.ticket.conjunctionTicketIndicator
  airline.ticket.customerReference
  airline.ticket.eTicket
  airline.ticket.exchangedTicketNumber
  airline.ticket.issue.address
  airline.ticket.issue.carrierCode
  airline.ticket.issue.carrierName
  airline.ticket.issue.city
  airline.ticket.issue.country
  airline.ticket.issue.date
  airline.ticket.issue.travelAgentCode
  airline.ticket.issue.travelAgentName
  airline.ticket.restricted
  airline.ticket.ticketNumber
  airline.ticket.totalFare
  airline.ticket.totalFees
  airline.ticket.totalTaxes
  airline.transactionType
  authorizationResponse.cardLevelIndicator
  authorizationResponse.cardSecurityCodeError
  authorizationResponse.commercialCard
  authorizationResponse.commercialCardIndicator
  authorizationResponse.date
  authorizationResponse.financialNetworkCode
  authorizationResponse.marketSpecificData
  authorizationResponse.merchantAdviceCode
  authorizationResponse.paySvcData
  authorizationResponse.posData
  authorizationResponse.posEntryMode
  authorizationResponse.posEntryModeChanged
  authorizationResponse.processingCode
  authorizationResponse.responseCode
  authorizationResponse.responseMessage
  authorizationResponse.returnAci
  authorizationResponse.stan
  authorizationResponse.time
  authorizationResponse.trackQuality
  authorizationResponse.transactionIdentifier
  authorizationResponse.validationCode
  authorizationResponse.vpasResponse
  billing.address.city
  billing.address.country
  billing.address.postcodeZip
  billing.address.stateProvince
  billing.address.street
  billing.address.street2
  billing.phone
  browserPayment.interaction.status
  browserPayment.interaction.timeCompleted
  browserPayment.interaction.timeInitiated
  browserPayment.interaction.timeRedirected
  browserPayment.interaction.timeReturned
  browserPayment.paypal.displayShippingAddress
  browserPayment.paypal.operation
  browserPayment.paypal.overrideShippingAddress
  browserPayment.paypal.paymentConfirmation
  browserPayment.redirectUrl
  browserPayment.returnUrl
  constraints.paymentPlans.numberOfDeferrals
  constraints.paymentPlans.numberOfPayments
  constraints.paymentPlans.supported
  currencyConversion.payerAcceptance
  currencyConversion.payerAmount
  currencyConversion.payerCurrency
  customer.ani
  customer.aniCallType
  customer.browser
  customer.email
  customer.hostname
  customer.ipAddress
  gatewayEntryPoint
  merchant
  order.amount
  order.creationTime
  order.currency
  order.customerNote
  order.customerOrderDate
  order.customerReference
  order.description
  order.id
  order.itemAmount
  order.item.description
  order.item.name
  order.item.quantity
  order.item.sku
  order.item.unitPrice
  order.item.unitTaxAmount
  order.notificationUrl
  order.productSKU
  order.reference
  order.requestorName
  order.shippingAndHandlingAmount
  order.status
  order.taxAmount
  order.taxRegistrationId
  order.totalAuthorizedAmount
  order.totalCapturedAmount
  order.totalRefundedAmount
  order.walletIndicator
  order.walletProvider
  partnerSolutionId
  paymentPlan.finalAmount
  paymentPlan.interestRate
  paymentPlan.numberOfDeferrals
  paymentPlan.numberOfPayments
  paymentPlan.paymentAmount
  paymentPlan.planId
  posTerminal.attended
  posTerminal.cardholderActivated
  posTerminal.entryMode
  posTerminal.inputCapability
  posTerminal.location
  posTerminal.name
  response.acquirerCode
  response.acquirerMessage
  response.cardSecurityCode.acquirerCode
  response.cardSecurityCode.gatewayCode
  response.cardholderVerification.avs.acquirerCode
  response.cardholderVerification.avs.gatewayCode
  response.cardholderVerification.detailedVerification.gatewayCode
  response.cardholderVerification.detailedVerification.type
  response.debugInformation
  response.gatewayCode
  response.risk.gatewayCode
  response.risk.reversalResult
  response.risk.review.decision
  response.risk.review.decisionReason
  response.risk.review.note
  response.risk.review.timeOfDecision
  response.risk.review.userId
  response.risk.rule.data
  response.risk.rule.id
  response.risk.rule.name
  response.risk.rule.recommendation
  response.risk.rule.score
  response.risk.rule.type
  response.risk.totalScore
  result
  shipping.address.city
  shipping.address.country
  shipping.address.postcodeZip
  shipping.address.stateProvince
  shipping.address.street
  shipping.address.street2
  shipping.firstName
  shipping.lastName
  shipping.method
  shipping.phone
  sourceOfFunds.provided.card.brand
  sourceOfFunds.provided.card.expiry.month
  sourceOfFunds.provided.card.expiry.year
  sourceOfFunds.provided.card.fundingMethod
  sourceOfFunds.provided.card.holder.firstName
  sourceOfFunds.provided.card.holder.lastName
  sourceOfFunds.provided.card.localBrand
  sourceOfFunds.provided.card.number
  sourceOfFunds.provided.card.scheme
  sourceOfFunds.provided.card.securityCodePresence
  sourceOfFunds.provided.card.sequenceNumber
  sourceOfFunds.provided.card.trackDataProvided
  sourceOfFunds.provided.giropay.bankIdentifier
  sourceOfFunds.provided.paypal.accountEmail
  sourceOfFunds.provided.paypal.accountHolder
  sourceOfFunds.provided.sofort.bankAccountHolder
  sourceOfFunds.provided.sofort.bankAccountNumber
  sourceOfFunds.provided.sofort.bankIdentifier
  sourceOfFunds.provided.sofort.bic
  sourceOfFunds.provided.sofort.country
  sourceOfFunds.provided.sofort.iban
  sourceOfFunds.token
  sourceOfFunds.type
  timeOfRecord
  transaction.acquirer.batch
  transaction.acquirer.customData
  transaction.acquirer.date
  transaction.acquirer.id
  transaction.acquirer.merchantId
  transaction.acquirer.time
  transaction.amount
  transaction.authorizationCode
  transaction.bancanet.merchantPaymentReference
  transaction.bancanet.paymentDueDate
  transaction.bancanet.paymentReason
  transaction.batchName
  transaction.cashAdvance
  transaction.currency
  transaction.frequency
  transaction.id
  transaction.item.description
  transaction.item.name
  transaction.item.quantity
  transaction.item.sku
  transaction.item.unitPrice
  transaction.item.unitTaxAmount
  transaction.merchantNote
  transaction.receipt
  transaction.reference
  transaction.source
  transaction.taxAmount
  transaction.terminal
  transaction.type
  userId
  version
)
